use std::{
    env,
    fs::File,
    io::{self, Write},
};

use emojis::Group;

const RECORD_SEPARATOR: char = '\u{001e}';
const FIELD_SEPARATOR: char = '\u{001f}';

struct Category {
    id: &'static str,
    label: &'static str,
    groups: &'static [Group],
}

const CATEGORIES: &[Category] = &[
    Category {
        id: "people",
        label: "People",
        groups: &[Group::SmileysAndEmotion, Group::PeopleAndBody],
    },
    Category {
        id: "nature",
        label: "Nature",
        groups: &[Group::AnimalsAndNature],
    },
    Category {
        id: "food",
        label: "Food",
        groups: &[Group::FoodAndDrink],
    },
    Category {
        id: "activities",
        label: "Activities",
        groups: &[Group::Activities],
    },
    Category {
        id: "travel",
        label: "Travel",
        groups: &[Group::TravelAndPlaces],
    },
    Category {
        id: "objects",
        label: "Objects",
        groups: &[Group::Objects],
    },
    Category {
        id: "symbols",
        label: "Symbols",
        groups: &[Group::Symbols],
    },
    Category {
        id: "flags",
        label: "Flags",
        groups: &[Group::Flags],
    },
];

fn main() -> io::Result<()> {
    let output_path = env::args_os()
        .nth(1)
        .expect("pass the generated TypeScript output path");
    let mut output = io::BufWriter::new(File::create(output_path)?);

    writeln!(
        output,
        "// Generated from emojis 0.9.0 (Unicode 17.0). Run `cargo run -p server --example export_emoji_catalog -- ui/src/lib/emojiCatalog.ts` to refresh."
    )?;
    writeln!(output, "// Do not edit this file by hand.\n")?;
    writeln!(
        output,
        "export type EmojiCategoryId =\n{};\n",
        CATEGORIES
            .iter()
            .map(|category| format!("  | {:?}", category.id))
            .collect::<Vec<_>>()
            .join("\n")
    )?;
    writeln!(
        output,
        "export interface EmojiCatalogEntry {{\n  emoji: string;\n  label: string;\n  searchText: string;\n  category: EmojiCategoryId;\n}}\n"
    )?;
    writeln!(
        output,
        "export const emojiCategories: ReadonlyArray<{{\n  id: EmojiCategoryId;\n  label: string;\n}}> = ["
    )?;
    for category in CATEGORIES {
        writeln!(
            output,
            "  {{ id: {:?}, label: {:?} }},",
            category.id, category.label
        )?;
    }
    writeln!(output, "];\n")?;
    writeln!(output, "const RECORD_SEPARATOR = \"\\u001e\";")?;
    writeln!(output, "const FIELD_SEPARATOR = \"\\u001f\";\n")?;
    writeln!(
        output,
        "const emojiData: Record<EmojiCategoryId, string> = {{"
    )?;
    for category in CATEGORIES {
        writeln!(output, "  {}: [", category.id)?;
        let mut records = Vec::new();
        for group in category.groups {
            for emoji in group.emojis() {
                let shortcodes = emoji.shortcodes().collect::<Vec<_>>().join(" ");
                let search_text = if shortcodes.is_empty() {
                    emoji.name().to_owned()
                } else {
                    format!("{} {}", emoji.name(), shortcodes)
                };
                records.push(format!(
                    "{}{}{}{}{}{}",
                    emoji.as_str(),
                    FIELD_SEPARATOR,
                    emoji.name(),
                    FIELD_SEPARATOR,
                    search_text,
                    RECORD_SEPARATOR,
                ));
            }
        }
        for chunk in records.chunks(4) {
            writeln!(
                output,
                "    {},",
                serde_json::to_string(&chunk.concat()).expect("emoji data is serializable")
            )?;
        }
        writeln!(output, "  ].join(\"\"),")?;
    }
    writeln!(output, "}};\n")?;
    writeln!(
        output,
        "function parseCategory(category: EmojiCategoryId): readonly EmojiCatalogEntry[] {{\n  return emojiData[category]\n    .slice(0, -RECORD_SEPARATOR.length)\n    .split(RECORD_SEPARATOR)\n    .map((record) => {{\n      const [emoji, label, searchText] = record.split(FIELD_SEPARATOR);\n      return {{ emoji, label, searchText, category }};\n    }});\n}}\n"
    )?;
    writeln!(
        output,
        "export const emojiCatalogByCategory = Object.fromEntries(\n  emojiCategories.map((category) => [category.id, parseCategory(category.id)]),\n) as Record<EmojiCategoryId, readonly EmojiCatalogEntry[]>;\n"
    )?;
    writeln!(
        output,
        "export const emojiCatalog: readonly EmojiCatalogEntry[] =\n  emojiCategories.flatMap((category) => emojiCatalogByCategory[category.id]);"
    )?;
    output.flush()
}
